# Chapter 3. Fast array operations with numpy and pandas

The multidimensional array, numpy.ndarray, is internally based on C arrays. Apart from the performance benefits, this choice allows NumPy code to easily interface with the existing C and FORTRAN routines

## 3.1 Getting started with numpy

### 3.1.1 Creating arrays

In [2]:
import numpy as np
a = np.array([0, 1,2])
a

array([0, 1, 2])

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([1,2,3], dtype = 'float32')
a

array([1., 2., 3.], dtype=float32)

In [6]:
a.astype('float32')

array([1., 2., 3.], dtype=float32)

In [7]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
a.shape

(2, 3)

In [9]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
a.shape

(16,)

In [13]:
a.reshape(4,4).shape

(4, 4)

In [14]:
a.shape = (4,4)
a.shape

(4, 4)

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3), dtype = 'float32')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [19]:
np.random.rand(3,3)

array([[0.24285472, 0.74470677, 0.13075692],
       [0.04206244, 0.78188362, 0.95643154],
       [0.9814878 , 0.5536925 , 0.93989009]])

In [20]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.empty_like(a)

array([[-8070450532247928832,  5764616314606123675,                    9,
                           0],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0, -8070450532247928832,
        -8070450532247928832]])

In [22]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 3.1.2 Accessing arrays

The NumPy array interface is, on a shallow level, similar to that of Python lists. NumPy arrays can be indexed using integers and iterated using a for loop

In [23]:
A = np.array([0,1,2,3,4,5,6,7,8])
A[0]

0

In [25]:
[a for a in A]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
A = np.array([[0,1,2],[3,4,5],[6,7,8]])
A[0]

array([0, 1, 2])

In [27]:
A[0,1]

1

In [28]:
A[(0,1)]

1

In [29]:
A[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
A[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [31]:
A[0,1] = 8
A[0:2, 0:2] = [[1,1], [1,1]]
A

array([[1, 1, 2],
       [1, 1, 5],
       [6, 7, 8]])

Indexing with the slicing syntax is very fast because, unlike lists, it doesn't produce a copy of the array. In NumPy's terminology, it returns a **view** of the same memory area. If we take a slice of the original array, and then we change one of its values, the original array will be updated as well

In [32]:
a = np.array([1,1,1,1])
a_view = a[0:2]
a_view[0] = 2
a

array([2, 1, 1, 1])

It is important to be extra careful when mutating NumPy arrays. Since views share data, changing the values of a view can result in hard-to-find bugs. To prevent side effects, you can set the *a.flags.writeable = False* flag, which will prevent accidental mutation of the array or any of its views

In [35]:
r_i = np.random.rand(10,2)
r_i

array([[0.71188891, 0.97204645],
       [0.37055878, 0.36735205],
       [0.66644029, 0.49979395],
       [0.68846535, 0.44809823],
       [0.48024954, 0.38949806],
       [0.26923391, 0.71762113],
       [0.439952  , 0.95715961],
       [0.75827493, 0.1148695 ],
       [0.06935974, 0.47051123],
       [0.16965382, 0.77473366]])

In [36]:
x_i = r_i[:,0]
x_i

array([0.71188891, 0.37055878, 0.66644029, 0.68846535, 0.48024954,
       0.26923391, 0.439952  , 0.75827493, 0.06935974, 0.16965382])

In [37]:
r_0 = r_i[0,:]
r_0

array([0.71188891, 0.97204645])

In [38]:
r_i[0]

array([0.71188891, 0.97204645])

Fancy indexing: index an array using another numpy array made of either integer or boolean values

In [39]:
a = np.array([9,8,7,6,5,4,3,2,1,0])
idx = np.array([0,2,3])
a[idx]

array([9, 7, 6])

In [ ]:
a = np.array([[0,1,2],[3,4,5],
              [6,7,8],[9,10,11]])
idx1 = np.array([0,1])
idx2 = np.array([2,3])
a[idx1, idx2]

In [43]:
a[np.array([0,1])]

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
a[[0,1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
a[0,1]

1

In [47]:
a[(0,1)]

1

In [48]:
a[0,1] == a[(0,1)]

True

In [50]:
a[np.array([0,1])] == a[[0,1]]

array([[ True,  True,  True],
       [ True,  True,  True]])

In [52]:
idx1 = [[0,1],[3,2]]
idx2 = [[0,2],[1,1]]
a[idx1, idx2]
# (0,0),(1,2),(3,1),(2,1)

array([[ 0,  5],
       [10,  7]])

In [54]:
r_i = np.random.rand(10,2)
r_i

array([[0.49484895, 0.00954873],
       [0.93346064, 0.24733568],
       [0.55020413, 0.55233446],
       [0.53774056, 0.38489638],
       [0.57466683, 0.92618917],
       [0.02872709, 0.52576388],
       [0.60381707, 0.10392372],
       [0.07931686, 0.13079175],
       [0.15641724, 0.81374236],
       [0.63291782, 0.18008601]])

In [55]:
r_i[:,[0,1]]

array([[0.49484895, 0.00954873],
       [0.93346064, 0.24733568],
       [0.55020413, 0.55233446],
       [0.53774056, 0.38489638],
       [0.57466683, 0.92618917],
       [0.02872709, 0.52576388],
       [0.60381707, 0.10392372],
       [0.07931686, 0.13079175],
       [0.15641724, 0.81374236],
       [0.63291782, 0.18008601]])

In [56]:
r_i[:,[1,0]]

array([[0.00954873, 0.49484895],
       [0.24733568, 0.93346064],
       [0.55233446, 0.55020413],
       [0.38489638, 0.53774056],
       [0.92618917, 0.57466683],
       [0.52576388, 0.02872709],
       [0.10392372, 0.60381707],
       [0.13079175, 0.07931686],
       [0.81374236, 0.15641724],
       [0.18008601, 0.63291782]])

In [57]:
r_i[:, [0, 1]] = r_i[:, [1, 0]]

In [58]:
r_i

array([[0.00954873, 0.49484895],
       [0.24733568, 0.93346064],
       [0.55233446, 0.55020413],
       [0.38489638, 0.53774056],
       [0.92618917, 0.57466683],
       [0.52576388, 0.02872709],
       [0.10392372, 0.60381707],
       [0.13079175, 0.07931686],
       [0.81374236, 0.15641724],
       [0.18008601, 0.63291782]])

When the index array is of the bool type, the rules are slightly different. The bool array will act like a mask; every element corresponding to True will be extracted and put in the output array

In [59]:
a = np.array([0,1,2,3,4,5])
mask = np.array([True, False, True, False, False, False])
a[mask]

array([0, 2])

The same rules apply when dealing with multiple dimensions. Furthermore, if the index array has the same shape as the original array, the elements corresponding to True will be selected and put in the resulting array.

Indexing in NumPy is a reasonably fast operation. Anyway, when speed is critical, you can use the slightly faster numpy.take and numpy.compress functions to squeeze out a little more performance. The first argument of numpy.take is the array we want to operate on, and the second is the list of indexes we want to extract. The last argument is axis; if not provided, the indexes will act on the flattened array; otherwise, they will act along the specified axis

In [61]:
r_i = np.random.rand(100,2)
idx = np.arange(50)

In [62]:
%timeit np.take(r_i, idx, axis = 0)

1.59 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [63]:
%timeit r_i[idx]

1.54 µs ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


The similar, but faster version for Boolean arrays is numpy.compress, which works in the same way.

In [64]:
idx = np.ones(100, dtype = 'bool')

In [67]:
%timeit np.compress(idx, r_i, axis = 0)

2.13 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [68]:
%timeit r_i[idx]

2.61 µs ± 37.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 3.1.3 Broadcasting

The true power of NumPy lies in its fast mathematical operations. The approach used by NumPy is to avoid stepping into the Python interpreter by performing element-wise calculation using optimized C code. Broadcasting is a clever set of rules that enables fast array calculations for arrays of similar (but not equal) shape

Whenever you do an arithmetic operation on two arrays (like a product), if the two operands have the same shape, the operation will be applied in an element-wise fashion. For example, upon multiplying two shape (2,2) arrays, the operation will be done between pairs of corresponding elements, producing another (2, 2) array,

In [69]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A * B
# 1*5, 2*6, 3*7, 4*8

array([[ 5, 12],
       [21, 32]])

If the shapes of the operands don't match, NumPy will attempt to match them using broadcasting rules. If one of the operands is a scalar (for example, a number), it will be applied to every element of the array

In [71]:
A * 2
# 1*2, 2*2, 3*2, 4*2

array([[2, 4],
       [6, 8]])

If the operand is another array, NumPy will try to match the shapes starting from the last axis. For example, if we want to combine an array of shape (3, 2) with one of shape (2,), the second array will be repeated three times to generate a (3, 2) array. In other words, the array is broadcasted along a dimension to match the shape of the other operand,

In [75]:
A = np.arange(6).reshape(3,2)
B = np.arange(2).reshape(2)

In [76]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
B

array([0, 1])

In [79]:
A + B

array([[0, 2],
       [2, 4],
       [4, 6]])

If the shapes mismatch, for example, when combining a (3, 2) array with a (2, 2) array, NumPy will throw an exception

In [ ]:
A = np.arange(6).reshape(3,2)
B = np.arange(4).reshape(2,2)
A + B

If one of the axis's size is 1, the array will be repeated over this axis until the shapes match

In [83]:
A = np.arange(100).reshape(5,10,2)
B = np.arange(10).reshape(5,1,2)

In [86]:
A + B # The B array will be repeated on the second axis 10 times of A 

array([[[  0,   2],
        [  2,   4],
        [  4,   6],
        [  6,   8],
        [  8,  10],
        [ 10,  12],
        [ 12,  14],
        [ 14,  16],
        [ 16,  18],
        [ 18,  20]],

       [[ 22,  24],
        [ 24,  26],
        [ 26,  28],
        [ 28,  30],
        [ 30,  32],
        [ 32,  34],
        [ 34,  36],
        [ 36,  38],
        [ 38,  40],
        [ 40,  42]],

       [[ 44,  46],
        [ 46,  48],
        [ 48,  50],
        [ 50,  52],
        [ 52,  54],
        [ 54,  56],
        [ 56,  58],
        [ 58,  60],
        [ 60,  62],
        [ 62,  64]],

       [[ 66,  68],
        [ 68,  70],
        [ 70,  72],
        [ 72,  74],
        [ 74,  76],
        [ 76,  78],
        [ 78,  80],
        [ 80,  82],
        [ 82,  84],
        [ 84,  86]],

       [[ 88,  90],
        [ 90,  92],
        [ 92,  94],
        [ 94,  96],
        [ 96,  98],
        [ 98, 100],
        [100, 102],
        [102, 104],
        [104, 106],
        [106

If we have a (5, 2) array and we want to combine it with one of shape (5, 10, 2), we can add an extra axis in the middle, as shown in the following code, to obtain a compatible (5, 1, 2) array

In [87]:
A = np.random.rand(5, 10, 2)
B = np.random.rand(5, 2)
A * B[:, np.newaxis, :]

array([[[1.48398230e-01, 2.61021576e-02],
        [1.27757715e-01, 3.81209117e-01],
        [6.71860427e-02, 1.91881651e-02],
        [4.00048174e-02, 6.50680971e-01],
        [1.03102388e-01, 7.77507554e-01],
        [9.84625429e-02, 3.23780869e-01],
        [1.68027062e-01, 1.14777894e-01],
        [1.06910521e-01, 4.33844716e-03],
        [1.90478166e-01, 1.77119174e-01],
        [1.86996355e-01, 2.73742703e-01]],

       [[1.50277337e-01, 5.39840667e-02],
        [5.79902585e-02, 4.44673431e-02],
        [1.00136000e-01, 1.19535551e-01],
        [1.67352588e-01, 2.52964532e-02],
        [1.31113360e-01, 1.14368606e-01],
        [9.88342935e-02, 9.15100907e-02],
        [7.52852249e-02, 8.28902416e-02],
        [7.29709075e-02, 3.26339827e-02],
        [1.56255656e-01, 7.51564143e-02],
        [6.96429548e-02, 3.98085528e-02]],

       [[2.49018264e-01, 4.84427814e-01],
        [4.99812267e-01, 2.88968273e-02],
        [6.47781314e-01, 1.27684657e-01],
        [4.51259326e-02, 4.682

Outer product: The outer product is a matrix containing the product of all the possible combinations (i, j) of the two array elements

To calculate this using NumPy, we will repeat the [a1, a2, a3] elements in one dimension, the [b1, b2, b3] elements in another dimension, and then take their elementwise product

In [97]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [99]:
a * b
# 1*4, 2*5, 3*6

array([ 4, 10, 18])

In [100]:
AB = a[:, np.newaxis] * b[np.newaxis, :]
AB
# 1*4, 1*5, 1*6
# 2*4, 2*5, 2*6
# 3*4, 3*5, 3*6

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

This operation is very fast and extremely effective as it avoids Python loops and is able to process a high number of elements at speeds comparable with pure C or FORTRAN code

### 3.1.4 Mathematical operations

In [101]:
np.sqrt(np.array([4,9,16]))

array([2., 3., 4.])

In [113]:
a = np.random.rand(5,3)
a > 0.3

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [114]:
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [115]:
a > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [116]:
a[a > 8]

array([ 9, 10, 11, 12, 13, 14])

In [119]:
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [120]:
a.sum(axis = 0)

array([30, 35, 40])

In [121]:
a.sum(axis = 1)

array([ 3, 12, 21, 30, 39])

In [123]:
a.sum() # With no argument operates on flattened array

105

### 3.1.5 Calculating the norm

In [ ]:
norm = sqrt(x ** 2 + y ** 2)

In [129]:
r_i = np.arange(20).reshape(10,2)
r_i

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [130]:
norm = np.sqrt((r_i ** 2).sum(axis = 1))
norm

array([ 1.        ,  3.60555128,  6.40312424,  9.21954446, 12.04159458,
       14.86606875, 17.69180601, 20.51828453, 23.34523506, 26.17250466])

## 3.2 Rewriting the particle simulator in numpy

In [ ]:
for i in range(nsteps):
    for p in self.particles:
        norm = (p.x**2 + p.y**2)**0.5
        v_x = (-p.y)/norm
        v_y = p.x/norm
        d_x = timestep * p.ang_vel * v_x
        d_y = timestep * p.ang_vel * v_y
        p.x += d_x
        p.y += d_y

In [ ]:
r_i = np.array([[p.x, p.y] for p in self.particles])
ang_vel_i = np.array([p.ang_vel for p in self.particles])

v_x = -y / norm
v_y = x / norm

norm_i = ((r_i ** 2).sum(axis=1))**0.5

v_i = r_i[:, [1, 0]] / norm_i
v_i[:, 0] *= -1

d_i = timestep * ang_vel_i[:, np.newaxis] * v_i
r_i += d_i

for i, p in enumerate(self.particles):
    p.x, p.y = r_i[i]

ParticleSimulator.evolve_python:

In [ ]:
def evolve_numpy(self, dt):
    timestep = 0.00001
    nsteps = int(dt/timestep)
    
    r_i = np.array([[p.x, p.y] for p in self.particles])
    ang_vel_i = np.array([p.ang_vel for p in self.particles])
    
    for i in range(nsteps):
        norm_i = np.sqrt((r_i ** 2).sum(axis=1))
        v_i = r_i[:, [1, 0]]
        v_i[:, 0] *= -1
        v_i /= norm_i[:, np.newaxis]
        d_i = timestep * ang_vel_i[:, np.newaxis] * v_i
        r_i += d_i
        
        for i, p in enumerate(self.particles):
            p.x, p.y = r_i[i]

In [ ]:
def benchmark(npart=100, method='python'):
    particles = [Particle(uniform(-1.0, 1.0),
                          uniform(-1.0, 1.0),
                          uniform(-1.0, 1.0))
                          for i in range(npart)]
    
simulator = ParticleSimulator(particles)

if method=='python':
    simulator.evolve_python(0.1)
elif method == 'numpy':
    simulator.evolve_numpy(0.1)

In [ ]:
from simul import benchmark
%timeit benchmark(100, 'python')
# 1 loops, best of 3: 614 ms per loop
%timeit benchmark(100, 'numpy')
# 1 loops, best of 3: 415 ms per loop

In [ ]:
%timeit benchmark(1000, 'python')
# 1 loops, best of 3: 6.13 s per loop
%timeit benchmark(1000, 'numpy')
# 1 loops, best of 3: 852 ms per loop

## 3.3 Reaching optimal performance with numexpr

When handling complex expressions, NumPy stores intermediate results in memory. A package called *numexpr* optimizes and compiles array expressions on the fly. It works by optimizing the usage of the CPU cache and by taking advantage of multiple processors.

In [135]:
import numexpr as ne
a = np.random.rand(10000)
b = np.random.rand(10000)
c = np.random.rand(10000)
d = ne.evaluate('a + b * c')

In [136]:
%timeit ne.evaluate('a + b * c')

61.1 µs ± 3.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [137]:
%timeit a + b * c

9.19 µs ± 218 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
x_ij = x_j - x_i
y_ij = y_j - y_i

d_ij = sqrt(x_ij**2 + y_ij**2)

r = np.random.rand(10000, 2)
r_i = r[:, np.newaxis]
r_j = r[np.newaxis, :]
d_ij = r_j - r_i

d_ij = np.sqrt((d_ij ** 2).sum(axis=2))

In [ ]:
r = np.random(10000, 2)
r_i = r[:, np.newaxis]
r_j = r[np.newaxis, :]

d_ij = ne.evaluate('sum((r_j - r_i)**2, 2)')
d_ij = ne.evaluate('sqrt(d_ij)')

from distance_matrix import (distance_matrix_numpy, distance_matrix_numexpr)

%timeit distance_matrix_numpy(10000)
# 1 loops, best of 3: 3.56 s per loop
%timeit distance_matrix_numexpr(10000)
# 1 loops, best of 3: 858 ms per loop

The numexpr package can be used every time you need to optimize a NumPy expression that involves large arrays and complex operations, and you can do so with minimal changes in the code

## 3.4 Pandas

### 3.4.1 Pandas fundamentals

While NumPy deals mostly with *arrays*, Pandas main data structures are *pandas.Series*, *pandas.DataFrame*, and *pandas.Panel*.

The main difference between a pd.Series object and an np.array is that a pd.Series object associates a specific key to each element of an array

In [139]:
import pandas as pd

patients = [0,1,2,3]
effective = [True, True, False, False]

effective_series = pd.Series(effective, index = patients)
effective_series

0     True
1     True
2    False
3    False
dtype: bool

In Pandas, keys are not limited to integers but can also be strings, floating point numbers, and also generic (hashable) Python objects

In [141]:
patients = ['a','b','c','d']
effective = [True, True, False, False]

effective_series = pd.Series(effective, index = patients)
effective_series

a     True
b     True
c    False
d    False
dtype: bool

An interesting observation is that, while NumPy arrays can be thought of as a contiguous collection of values similar to Python lists, the Pandas pd.Series object can be thought of as a structure that maps keys to values, similar to Python dictionaries.

pd.DataFrame can be initialized, similarly to a pd.Series object, by passing a dictionary of columns and an index. 

In [142]:
patients = ['a','b','c','d']

columns = {
    "sys_initial": [120, 126, 130, 115],
    "dia_initial": [75, 85, 90, 87],
    "sys_final": [115, 123, 130, 118],
    "dia_final": [70, 82, 92, 87]
}

df = pd.DataFrame(columns, index = patients)
df

sys_initial  dia_initial  sys_final  dia_final
a          120           75        115         70
b          126           85        123         82
c          130           90        130         92
d          115           87        118         87

pd.DataFrame as a collection of pd.Series

In [143]:
columns = {
    "sys_initial": pd.Series([120, 126, 130, 115], index=patients),
    "dia_initial": pd.Series([75, 85, 90, 87], index=patients),
    "sys_final": pd.Series([115, 123, 130, 118], index=patients),
    "dia_final": pd.Series([70, 82, 92, 87], index=patients)
}

df = pd.DataFrame(columns)
df

sys_initial  dia_initial  sys_final  dia_final
a          120           75        115         70
b          126           85        123         82
c          130           90        130         92
d          115           87        118         87

In [144]:
effective_series.head()

a     True
b     True
c    False
d    False
dtype: bool

In [145]:
df.head()

sys_initial  dia_initial  sys_final  dia_final
a          120           75        115         70
b          126           85        123         82
c          130           90        130         92
d          115           87        118         87

Just like a pd.DataFrame can be used to store a collection of pd.Series, you can use a pd.Panel to store a collection of pd.DataFrames.

#### Indexing Series and DataFrame objects

In [146]:
effective_series.loc['a']

True

In [147]:
effective_series.iloc[0]

True

In [153]:
effective_series['a']

True

In [154]:
effective_series[0]

True

In [155]:
df.loc['a']

sys_initial    120
dia_initial     75
sys_final      115
dia_final       70
Name: a, dtype: int64

In [156]:
df.iloc[0]

sys_initial    120
dia_initial     75
sys_final      115
dia_final       70
Name: a, dtype: int64

In [159]:
df.loc['a', 'sys_initial']

120

In [160]:
df.loc['a'].loc['sys_initial']

120

In [161]:
df.iloc[0,1]

75

In [162]:
df.iloc[0].iloc[1]

75

In [164]:
df['sys_initial']

a    120
b    126
c    130
d    115
Name: sys_initial, dtype: int64

In [166]:
df.sys_initial

a    120
b    126
c    130
d    115
Name: sys_initial, dtype: int64

In [167]:
df[df.columns[2]]

a    115
b    123
c    130
d    118
Name: sys_final, dtype: int64

In [168]:
df.iloc[:,2]

a    115
b    123
c    130
d    118
Name: sys_final, dtype: int64

There are some differences between an index in Pandas and a dictionary. For example, while the keys of a dictionary cannot contain duplicates, Pandas indexes can contain repeated elements. This flexibility, however, comes at a cost--if we try to access an element in a non-unique index, we may incur substantial performance loss--the access will be O(N), like a linear search, rather than O(1), like a dictionary

A way to mitigate this effect is to sort the index; this will allow Pandas to use a binary search algorithm with a computational complexity of O(log(N)), which is much better. This can be accomplished using the pd.Series.sort_index function

In [169]:
# Create a series with duplicate index
index = list(range(1000)) + list(range(1000))

# Accessing a normal series is a O(N) operation 
series = pd.Series(range(2000), index = index)

# Sorting the will improve look-up scaling to O(log(N))
series.sort_index(inplace = True)

Unique index, O(1)

Non unique index, O(N)

Non unique sorted index, O(log(N))

### 3.4.2 Database-style operations with pandas

#### Mapping

Pandas supports element-wise operations just like NumPy (after all, pd.Series stores their data using np.array)

In [171]:
np.log(df.sys_initial) # Logarithm of a series

a    4.787492
b    4.836282
c    4.867534
d    4.744932
Name: sys_initial, dtype: float64

In [172]:
df.sys_initial ** 2 # Square a series

a    14400
b    15876
c    16900
d    13225
Name: sys_initial, dtype: int64

In [173]:
np.log(df) # Logarithm of a dataframe

sys_initial  dia_initial  sys_final  dia_final
a     4.787492     4.317488   4.744932   4.248495
b     4.836282     4.442651   4.812184   4.406719
c     4.867534     4.499810   4.867534   4.521789
d     4.744932     4.465908   4.770685   4.465908

In [174]:
df ** 2 # Square of a dataframe

sys_initial  dia_initial  sys_final  dia_final
a        14400         5625      13225       4900
b        15876         7225      15129       6724
c        16900         8100      16900       8464
d        13225         7569      13924       7569

Perform element-wise operations between two pd.Series in a way similar to NumPy. An important difference is that the operands will be matched by key, rather than by position; if there is a mismatch in the index, the resulting value will be set to NaN

In [175]:
# Matching index
a = pd.Series([1,2,3], index = ['a','b','c'])
b = pd.Series([4,5,6], index = ['a','b','c'])
a + b

a    5
b    7
c    9
dtype: int64

In [177]:
# Mismatching index
b = pd.Series([4,5,6], index = ['a','b','d'])
a + b 

a    5.0
b    7.0
c    NaN
d    NaN
dtype: float64

The pd.Series.map method can be used to execute a function to each value and return a pd.Series containing each result

In [178]:
a = pd.Series([1,2,3], index = ['a','b','c'])

def superstar(x):
    return '*' + str(x) + '*'

a.map(superstar)

a    *1*
b    *2*
c    *3*
dtype: object

The pd.DataFrame.applymap function is the equivalent of pd.Series.map, but for DataFrames

In [179]:
df.applymap(superstar)

sys_initial dia_initial sys_final dia_final
a       *120*        *75*     *115*      *70*
b       *126*        *85*     *123*      *82*
c       *130*        *90*     *130*      *92*
d       *115*        *87*     *118*      *87*

Tthe pd.DataFrame.apply function can apply the passed function to each column or each row, rather than element-wise. The selection can be performed with the argument axis, where a value of 0 (the default) corresponds to columns, and 1 corresponds to rows. Also, note that the return value of apply is a pd.Series

In [181]:
df.apply(superstar, axis = 0)

sys_initial    *a    120\nb    126\nc    130\nd    115\nName:...
dia_initial    *a    75\nb    85\nc    90\nd    87\nName: dia...
sys_final      *a    115\nb    123\nc    130\nd    118\nName:...
dia_final      *a    70\nb    82\nc    92\nd    87\nName: dia...
dtype: object

In [182]:
df.apply(superstar, axis = 1)

a    *sys_initial    120\ndia_initial     75\nsys_f...
b    *sys_initial    126\ndia_initial     85\nsys_f...
c    *sys_initial    130\ndia_initial     90\nsys_f...
d    *sys_initial    115\ndia_initial     87\nsys_f...
dtype: object

Pandas also supports efficient numexpr-style expressions with the convenient *eval* method

In [183]:
df.eval('sys_final - sys_initial')

a   -5
b   -3
c    0
d    3
dtype: int64

It is also possible to create new columns using the assignment operator in the pd.DataFrame.eval expression. Note that, if the inplace=True argument is used, the operation will be applied directly on the original pd.DataFrame; otherwise, the function will return a new dataframe.

In [185]:
df.eval("sys_delta = sys_final - sys_initial", inplace=False)

sys_initial  dia_initial  sys_final  dia_final  sys_delta
a          120           75        115         70         -5
b          126           85        123         82         -3
c          130           90        130         92          0
d          115           87        118         87          3

#### Grouping, aggregations, and transforms

In [187]:
patients = ['a','b','c','d','e','f']

columns = {
    "sys_initial": [120, 126, 130, 115, 150, 117],
    "dia_initial": [75, 85, 90, 87, 90, 74],
    "sys_final": [115, 123, 130, 118, 130, 121],
    "dia_final": [70, 82, 92, 87, 85, 74],
    "drug_admst": [True, True, True, True, False, False]
}

df = pd.DataFrame(columns, index = patients)
df

sys_initial  dia_initial  sys_final  dia_final  drug_admst
a          120           75        115         70        True
b          126           85        123         82        True
c          130           90        130         92        True
d          115           87        118         87        True
e          150           90        130         85       False
f          117           74        121         74       False

In [189]:
df.groupby('drug_admst')

for value, group in df.groupby('drug_admst'):
    print("Value: {}".format(value))
    print("Group DataFrame:")
    print(group)

Value: False
Group DataFrame:
   sys_initial  dia_initial  sys_final  dia_final  drug_admst
e          150           90        130         85       False
f          117           74        121         74       False
Value: True
Group DataFrame:
   sys_initial  dia_initial  sys_final  dia_final  drug_admst
a          120           75        115         70        True
b          126           85        123         82        True
c          130           90        130         92        True
d          115           87        118         87        True


In [190]:
df.groupby('drug_admst').agg(np.mean)

sys_initial  dia_initial  sys_final  dia_final
drug_admst                                                
False            133.50        82.00      125.5      79.50
True             122.75        84.25      121.5      82.75

It is also possible to perform processing on the DataFrame groups that do not represent a summarization. One common example of such an operation is filling in missing values. Those intermediate steps are called transforms

In [192]:
df.loc['a','sys_initial'] = None
df.groupby('drug_admst').transform(lambda df: df.fillna(df.mean()))

sys_initial  dia_initial  sys_final  dia_final
a   123.666667           75        115         70
b   126.000000           85        123         82
c   130.000000           90        130         92
d   115.000000           87        118         87
e   150.000000           90        130         85
f   117.000000           74        121         74

#### Joining

In [193]:
hospitals = pd.DataFrame(
    { "name" : ["City 1", "City 2", "City 3"],
      "address" : ["Address 1", "Address 2", "Address 3"],
      "city": ["City 1", "City 2", "City 3"] },
    index=["H1", "H2", "H3"])

hospital_id = ["H1", "H2", "H2", "H3", "H3", "H3"]

df['hospital_id'] = hospital_id
df

sys_initial  dia_initial  sys_final  dia_final  drug_admst hospital_id
a          NaN           75        115         70        True          H1
b        126.0           85        123         82        True          H2
c        130.0           90        130         92        True          H2
d        115.0           87        118         87        True          H3
e        150.0           90        130         85       False          H3
f        117.0           74        121         74       False          H3

In [194]:
hospitals

name    address    city
H1  City 1  Address 1  City 1
H2  City 2  Address 2  City 2
H3  City 3  Address 3  City 3

In [196]:
hospital_dict = {
    "H1": ("City 1", "Name 1", "Address 1"),
    "H2": ("City 2", "Name 2", "Address 2"),
    "H3": ("City 3", "Name 3", "Address 3")
}

cities = [hospital_dict[key][0]
            for key in hospital_id]
cities

['City 1', 'City 2', 'City 2', 'City 3', 'City 3', 'City 3']

This algorithm runs efficiently with an O(N) time complexity, where N is the size of hospital_id. Pandas allows you to encode the same operation using simple indexing; the advantage is that the join will be performed in heavily optimized Cython and with efficient hashing algorithms.

In [197]:
cities = hospitals.loc[hospital_id, "city"]
cities

H1    City 1
H2    City 2
H2    City 2
H3    City 3
H3    City 3
H3    City 3
Name: city, dtype: object

In [198]:
result = df.join(hospitals, on = 'hospital_id')
result

sys_initial  dia_initial  sys_final  dia_final  drug_admst hospital_id  \
a          NaN           75        115         70        True          H1   
b        126.0           85        123         82        True          H2   
c        130.0           90        130         92        True          H2   
d        115.0           87        118         87        True          H3   
e        150.0           90        130         85       False          H3   
f        117.0           74        121         74       False          H3   

     name    address    city  
a  City 1  Address 1  City 1  
b  City 2  Address 2  City 2  
c  City 2  Address 2  City 2  
d  City 3  Address 3  City 3  
e  City 3  Address 3  City 3  
f  City 3  Address 3  City 3

## 3.5 Summary

NumPy and Pandas work well when handling large, homogenous inputs, but they are not suitable when the expressions grow complex and the operations cannot be expressed using the tools provided by these libraries. In such cases, we can leverage Python capabilities as a glue language by interfacing it with C using the Cython package.